/*
File: makefile

Created: 24-03-26
Author: 이성희
*/
main: main_ver3.o function_ver3.o header_ver3.o
  gcc -o test main_ver3.c function_ver3.c header_ver3.h

header_ver3.o : header_ver3.h
  gcc -c header_ver3.h

main_ver3.o : main_ver3.c
  gcc -c main_ver3.c

function_ver3.o : function_ver3.c
  gcc -c function_ver3.c

